name: financial_instruments
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cloud_firestore: ^4.7.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_otp_text_field: ^1.1.1
  flutter_secure_storage: ^8.0.0
  get_it: ^7.6.0
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  injectable: ^2.1.1
  json_annotation: ^4.8.1


dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.2
  lint: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSans/NotoSans-BlackItalic.ttf
          style: italic
          weight: 900

        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSans-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: assets/fonts/NotoSans/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans/NotoSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800

        - asset: assets/fonts/NotoSans/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSans/NotoSans-ExtraLightItalic.ttf
          style: italic
          weight: 200

        - asset: assets/fonts/NotoSans/NotoSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
          weight: 400

        - asset: assets/fonts/NotoSans/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans/NotoSans-LightItalic.ttf
          style: italic
          weight: 300

        - asset: assets/fonts/NotoSans/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans/NotoSans-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: assets/fonts/NotoSans/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans/NotoSans-SemiBoldItalic.ttf
          style: italic
          weight: 600

        - asset: assets/fonts/NotoSans/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSans/NotoSans-ThinItalic.ttf
          style: italic
          weight: 100
